id: I923CC2E8
ocr_import_info:
  timestamp: '2023-06-28T07:55:22.553984+00:00'
  batch_id: batch-8c5a
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 08:03:27.370313+00:00
last_modified: 2023-06-28 08:03:27.370319+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM1318
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM1318
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྣམ་འགྲེལ་གྱི་རྩ་བ།
  languages:
  - bo
  author: ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9791778004686387
  ocr_word_median_confidence_index: 0.9998599
bases:
  I1NLM1318_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM1318_001
      total_pages: 460
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM1318_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9998599
      ocr_word_mean_confidence_index: 0.9791778004686387
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
